parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmIMage: ${{ parameters.vmImage }}
  variables:
    DEPENDS: "cython numpy matplotlib h5py nibabel cvxpy tqdm"
    VENV_ARGS: "--python=python"
    INSTALL_TYPE: "setup"
    PRE_WHEELS: "https://pypi.anaconda.org/scipy-wheels-nightly/simple"
  strategy:
    # maxParallel: 4
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(python.version)
      architecture: 'x64'
      addToPath: true
  - bash: |
      sudo apt-get update
      sudo apt-get install -y libhdf5-serial-dev
    displayName: 'Install packages'
  - bash: |
      sudo apt-get install -y xvfb
      /usr/bin/Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: 'Install Xvfb package'
    condition: and(succeeded(), eq( variables['TEST_WITH_XVFB'], '1' ))
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
    condition: eq( variables['INSTALL_TYPE'], 'conda' )
  - script: |
      sudo chmod +x ci/azure/install.sh
      ./ci/azure/install.sh
    displayName: 'Install dependencies'
  - script: |
      sudo chmod +x ci/azure/script.sh
      ./ci/azure/script.sh
    displayName: 'Install DIPY and Run Tests'
