name: Optional Deps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PIP_CONDA:
    uses: skoudoro/dipy/.github/workflows/test_template.yml@gh-actions
    with:
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      install-type: '["conda", "pip"]'
      extra-depends: scikit_learn pandas statsmodels tables scipy
