name: Visualization

on:
  push:
    branches: [ master ]
    paths:
      - dipy/viz/**
      - dipy/workflows/**
  pull_request:
    branches: [ master ]
    paths:
      - dipy/viz/**
      - dipy/workflows/**

jobs:
  VIZ:
    uses: skoudoro/dipy/.github/workflows/test_template.yml@gh-actions
    with:
      runs-on: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      extra-depends: scikit_learn vtk fury scipy