name: PRE_WHEELS

on:
  push:
    branches: [ master ]
    paths:
      - dipy/viz/**
      - dipy/workflows/**
  pull_request:
    branches: [ master ]
    paths:
      - dipy/viz/**
      - dipy/workflows/**

jobs:
  PRE:
    uses: skoudoro/dipy/.github/workflows/test_template.yml@gh-actions
    with:
      runs-on: '["ubuntu-latest", ]'
      use-pre: true
      extra-depends: scikit_learn scipy statsmodels pandas tables