name: DIPY  Base Workflow Template

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Select on which environment you want to run the workflow"
        type: string
        required: false
        default: '"ubuntu-latest"'
      python-version:
        description: "Select Python version"
        type: string
        required: false
        default: '"3.9"'
      use-pre:
        description: "bal"
        type: boolean
        required: false
      install-type:
        description: ""
        type: string
        required: false
        default: "'setup'"
      depends:
        description: ""
        type: string
        required: false
        default: '"cython" "numpy" "matplotlib" "h5py" "nibabel" "cvxpy" "tqdm"'
      extra-depends:
        description: ""
        type: string
        required: false
        default: ""

    secrets:
      token:
        required: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{fromJSON(inputs.python-version) }}
        os: ${{fromJSON(inputs.runs-on) }}
        install-type: ${{fromJSON(inputs.install-type) }}
    env:
      DEPENDS: ${{fromJSON(inputs.depends) }}
      EXTRA_DEPENDS: ${{fromJSON(inputs.extra-depends) }}
      INSTALL_TYPE: ${{ matrix.install-type }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      VENV_ARGS: "--python=python"
      # CHECK_TYPE: ${{ matrix.check }}
      # EXTRA_PIP_FLAGS: ${{ matrix.pip-flags }}
      PRE_WHEELS: "https://pypi.anaconda.org/scipy-wheels-nightly/simple"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: tools/ci/install_dependencies.sh
    - name: Install DIPY
      run: tools/ci/install.sh
    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
    - name: Run the Tests
      run: tools/ci/run_tests.sh